[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "ubittool"
version = "0.8.0"
description = "Tool to interface with the BBC micro:bit."
authors = [
  { name = "Carlos Pereira Atencio", email = "carlosperate@embeddedlog.com" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8, <3.14"
keywords = ["microbit", "micro:bit", "bbcmicrobit", "ubittool"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Environment :: MacOS X",
  "Environment :: Win32 (MS Windows)",
  "Environment :: X11 Applications",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: End Users/Desktop",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Topic :: Education",
  "Topic :: Software Development :: Embedded Systems",
]
dependencies = [
  "IntelHex>=2.2.1",
  "uflash>=1.1.0,<1.2.1",
  "pyocd==0.36.0",
  "click>=7.0",
]

[dependency-groups]
dev = [
  "pyinstaller>=5.13.2",
  "macholib>=1.8; sys_platform == 'darwin'",
  "pywin32>=303; sys_platform == 'win32'",
  "pywin32-ctypes>=0.2.0; sys_platform == 'win32'",
  # PyOCD needs this as a setup_requires, for some reason 'pipenv install' in
  # Travis doesn't pick it up and PyOCD fails to install or run
  "setuptools_scm",
  "ruff",
  "pytest>=7.4.3",
  "pytest-cov>=4.1.0",
]

[project.scripts]
ubit = "ubittool.__main__:main"

[project.urls]
Homepage = "https://carlosperate.github.io/ubittool/"
Repository = "https://github.com/carlosperate/ubittool/"
Documentation = "https://carlosperate.github.io/ubittool/"

[tool.ruff]
line-length = 79
target-version = "py38"
exclude = [
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "_build",
  "buck-out",
  "build",
  "dist",
  "ignoreme",
]

[tool.ruff.lint]
# Enable Pyflakes (F) and a subset of the pycodestyle (E) codes by default.
select = ["E4", "E7", "E9", "F"]
ignore = []
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.coverage.run]
branch = false

[tool.coverage.report]
show_missing = true
# Regexes for lines to exclude from consideration
exclude_lines = [
  # Have to re-enable the standard pragma
  "pragma: no cover",
  # Don't complain about missing debug-only code:
  "def __repr__",
  "if self.debug",
  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",
  # Don't complain if non-runnable code isn't run:
  "if 0:",
  "if __name__ == .__main__.:",
]

[tool.coverage.html]
directory = "htmlcov"
