name: Build Executables

on: [push, pull_request]

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        # macOS 15 Intel runner is x86_64 and macOS 14 runner is arm64
        os: [ubuntu-22.04, macos-15-intel, macos-14, windows-2019]
      fail-fast: false
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install ubittool dependencies
        run: uv sync --python 3.11
      - name: Run PyInstaller
        run: uv run python make.py build
      # GitHub actions upload artifact breaks permissions, so tar workaround
      # https://github.com/actions/upload-artifact/issues/38
      - name: Tar files
        run: tar -cvf ubittool-${{ runner.os }}-${{ runner.arch }}.tar dist
      - uses: actions/upload-artifact@v6
        with:
          name: ubittool-${{ runner.os }}-${{ runner.arch }}
          path: ubittool-${{ runner.os }}-${{ runner.arch }}.tar
      # Run the tests as the last step, we might still want the installed to be
      # uploaded, but we should catch issues runnning the tests,
      # specifically the GitHub Python builds with tkinker in macOS
      - name: Run tests
        if: runner.os != 'Linux'
        run: uv run python make.py check
      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
          xvfb-run uv run python make.py check
