name: Build Executables

on: [push, pull_request]

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
      fail-fast: false
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Force poetry install without lock file when not macOS
        if: runner.os != 'macOS'
        run: rm poetry.lock
      - name: Install ubittool dependencies
        run: poetry install
      - name: Run PyInstaller
        run: poetry run python make.py build
      # GitHub actions upload artifact breaks permissions, so tar workaround
      # https://github.com/actions/upload-artifact/issues/38
      - name: Tar files
        run: tar -cvf ubittool-${{ runner.os }}.tar dist
      - uses: actions/upload-artifact@v1
        with:
          name: ubittool-${{ runner.os }}
          path: ubittool-${{ runner.os }}.tar
      # Run the tests as the last step, we might still want the installed to be
      # uploaded, but we should catch issues runnning the tests,
      # specifically the GitHub Python builds with tkinker in macOS
      - name: Run tests
        if: runner.os != 'Linux'
        run: poetry run python make.py check
      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
          xvfb-run poetry run python make.py check
