name: Test

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        # There are issues with Tkinter & Python in the GH Actions environment
        # So we control which exact minor versions are used, which are known to
        # work, but unfortunately don't have a release for the Windows runner
        # The latest Python 3.7 to 3.10 minor releases have this tkinter error:
        #   RuntimeError: tk.h version (8.5) doesn't match libtk.a version (8.6)
        #   https://github.com/actions/setup-python/issues/649
        exclude:
          - os: macos-11
        include:
          - os: macos-11
            python-version: "3.7.15"
          - os: macos-11
            python-version: "3.8.15"
          - os: macos-11
            python-version: "3.9.15"
          - os: macos-11
            python-version: "3.10.10"
          - os: macos-11
            python-version: "3.11"
      fail-fast: false
    name: Py ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Install ubittool dependencies
        run: poetry install --verbose
      - name: Prepare Ubuntu xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
      - name: Run tests (Ubuntu)
        if: runner.os == 'Linux'
        run: xvfb-run poetry run python make.py check
      - name: Run tests
        if: runner.os != 'Linux'
        run: poetry run python make.py check
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
